### ISSUE TITLE
Create an empty `.gdignore` file in the output directory to prevent Godot from importing the output images as resources

### ISSUE THREAD

**Issue by Calinou** [AhmedElTabarani/AnimationRecorder#5]
This will prevent Godot from temporarily freezing when the animation is saved and you focus on the Godot editor again.

**Comment by AhmedElTabarani** [comment]
Oh, That is incredible, thank you <3

**Comment by AhmedElTabarani** [comment]
It is back to normal, after reset to HEAD, and sometimes it  doesn't work again, and sometimes it works and back to normal
I think that there are some cases that broke it, I will do more tests for it, sorry for disturbing you.
